- packages/api/resolvers/types/order.js
meta always return null because the underlying property is `context`
> fix: cart/order has no meta

- packages/api/errors.js
- packages/api/getCart.js
- packages/api/resolvers/mutations/addCartDiscount.js
- packages/api/resolvers/mutations/addCartProduct.js
- packages/api/resolvers/mutations/addCartQuotation.js
- packages/api/resolvers/mutations/checkoutCart.js
- packages/api/resolvers/mutations/createCart.js
- packages/api/resolvers/mutations/emptyCart.js
- packages/api/resolvers/mutations/index.js
- packages/api/resolvers/mutations/updateCart.js
- packages/api/resolvers/queries/orders.js
- packages/api/resolvers/types/user.js
- packages/api/roles/all.js
- packages/api/roles/index.js
- packages/api/roles/loggedIn.js
- packages/api/schema/mutation.js
- packages/api/schema/types/user.js
- packages/core-orders/db/orders/helpers.js
- packages/core-orders/db/orders/schema.js
This will add multi-cart support in a way that does not interfer with the standard way of having just one cart per user. Through a new mutation one can add a new cart by providing a unique orderNumber.
If you just use the cart mutations like before and do a checkout without providing an actual orderId, the first cart in order of creation is assumed. If you have 3 carts and do 3 checkouts, this represents a queue: Each time checkout get's called, the oldest cart gets checked out.
New mutation:
```graphql
createCart(orderNumber: String!): Order
```
Enhances User:
Changes
```graphql
orders(includeDrafts: Boolean = false): [Order!]!
```
to
```graphql
orders(includeCarts: Boolean = false): [Order!]!
```
Even if it looks like it does introduce a breaking change, in fact it does not as …
> Multi-cart

- packages/api/resolvers/queries/products.js
small change: products resolver sorts now by sequence instead of published-date. If severall products have same sequence, it would sort by published as before
> fix: sort products by sequence

- packages/core-products/db/product-media/schema.js
- packages/core-products/db/product-reviews/schema.js
- packages/core-products/db/product-variations/schema.js
- packages/core-products/db/products/schema.js
this PR removes the validation of `SimpleSchema.RegEx.Id` on all Ids and replaces it with simple String.
While it is generally preferable to have non-guessable IDs, it sometimes make sense to have predefined IDs, in particular if you import products or similar from external sources.
This change does not change any default behaviour, it just allows to pass any string s ID when you create a Product
> relax ID restriction

- examples/minimal/boot.js
If introspection is disabled, the control-panel does not work. It needs introspection to populate the type drop-downs.
> Enable introspection for example

- packages/api/resolvers/mutations/addMultipleCartProducts.js
- packages/api/resolvers/mutations/index.js
- packages/api/schema/inputTypes.js
- packages/api/schema/mutation.js
workaround for https://github.com/unchainedshop/unchained/issues/26
adds a new new mutation `addMultipleCartProducts`
does not fix the underlying concurrency problem though, but i think this is one obvious usecase were you can run into that problem.
> feat: allow to add multiple cart products in one request

- examples/minimal/boot.js
- packages/api/resolvers/types/order-delivery-pickup.js
- packages/api/schema/mutation.js
- packages/api/schema/types/geo-position.js
- packages/api/schema/types/index.js
- packages/api/schema/types/order/delivery.js
- packages/api/schema/types/order/index.js
- packages/api/schema/types/order/pick-up-location.js
- packages/core-delivery/db/helpers.js
- packages/core-delivery/director.js
- packages/core-delivery/plugins/pick-mup.js
- packages/core-delivery/plugins/post.js
- packages/core-warehousing/plugins/google-sheets.js
- adds all/active pickupLocations feature to pickup providers, 
- removes address from Pickup providers (breaking)
- adds Pick-M-Up Dummy plugin to test the feature
OrderPickupDelivery.pickUpLocations
OrderPickupDelivery.activePickUpLocation
OrderPickUpLocation
GeoPosition
> Extend Pick Up Delivery Providers with PickUp Locations data

- packages/core-worker/plugins/http-request.js
Only try to parse JSON if the content is actually marked as JSON. Otherwise, just use the response as text.
> Fix: Worker: Only parse JSON if it is JSON

- packages/api/resolvers/mutations/bookmark.js
- packages/api/schema/mutation.js
Currently when removing a bookmark using the `bookmark` mutation unchained will return `null`:
```gql
bookmark(
productId: ID!
bookmarked: Boolean = true
): Bookmark
```
This pr changes this behaviour by returning the removed bookmark. The `removeBookmark` mutation already behaves like this.
> endpoint returns deleted bookmark

- packages/api/schema/types/money.js
- packages/core-delivery/plugins/send-mail.js
- packages/core-pricing/plugins/product-catalog-price.js
- packages/core-products/db/products/helpers.js
- tests/helpers.js
- tests/product-reviews.test.js
- tests/products.test.js
- tests/seeds/warehousings.js
- tests/setup-delivery.test.js
- tests/setup-payment.test.js
- tests/setup-warehousing.test.js
Breaking:
- Products: catalogPrice is now "null" instead of a price with amount 0 if there was no price found, this allows to distingish between products where the price calculation failed and products which are in fact free
- Products: same for simulatedPrice when the default catalog price pricing plugin can not find any price in the database
- API: Money: amount & currency are now required graphql fields (!), this should improve dx for typescript users that use typescript type generation from graphql
Also:
- Tests ;)
> Tests providers

- packages/api/resolvers/mutations/createFilter.js
- packages/api/resolvers/mutations/removeFilter.js
- packages/api/resolvers/mutations/updateFilter.js
- packages/core-filters/db/helpers.js
- packages/core-filters/plugins/local-search.js
- packages/core-filters/search/index.js
- packages/core-filters/search/resolve-filter-selector.js
- tests/filters.test.js
- tests/helpers.js
- tests/seeds/assortments.js
- tests/seeds/filters.js
- tests/seeds/products.js
Breaking:
- Full text search now correctly returns an empty resultset if the search has been upfront limited by a productId list of 0 array items (fixes an edge case with the local search provider)
- Unscoped Faceted search now returns all active filters when the local-search plugin is activated
- Unscoped Faceted search now returns even inactive filters if the filterQuery has a key of an existent filter
Minor:
- Allow skipInvalidation flags on createFilter and updateFilter
> Tests filters

- examples/controlpanel/components/BreadcrumbTrail.jsx
A remedy for https://github.com/unchainedshop/unchained/issues/162
Remove `edit` prefix as it leads to stacking creating resolvable routes.
Example: http://localhost:4000/assortments/edit/edit?_id=wsmjf93iBBQirEoEc
> Breadcrumb link fix

- examples/controlpanel/components/assortments/AssortmentGraph.jsx
- examples/controlpanel/components/assortments/CytoscapeComponent.jsx
This PR relies on `cy` prop to set up event listeners to invoke the fetch and display logic for linked assortments of a node(assortment). 
The two event listeners are:
- `cy.on 'tap', 'node'`
This event listens to clicks/taps on nodes and then fetches the linked assortments using Apollo client:
```
const { data } = await client.query({
query: GET_ASSORTMENT_LINKS,
variables: { assortmentId: node.id() },
});
```
- `cy.on 'add', node`
```
cy.on('add', 'node', () => {
cy.layout(layout).run();
cy.fit();
});
```
The listens to the the addition of any new nodes and invokes(resets) the layout to avoid stacking the nodes on top of each other.
> Add nodes on-click 

- examples/controlpanel/components/SearchDropdown.jsx
- examples/controlpanel/components/assortments/AssortmentGraph.jsx
- examples/controlpanel/components/assortments/AssortmentList.jsx
- examples/controlpanel/components/assortments/FormNewAssortmentLink.jsx
- examples/controlpanel/components/assortments/FormNewAssortmentProduct.jsx
- examples/controlpanel/components/products/ProductList.jsx
- examples/controlpanel/components/searchQueries.jsx
- examples/controlpanel/components/users/UserList.jsx
Adding the front end part for https://github.com/unchainedshop/unchained/issues/226. The `SearchDropdown` component is getting reused more and more, so I decided to move the graphql search queries outside and have them set as props to allow for more general use cases.
> User search dropdown

- examples/controlpanel/components/orders/OrderList.jsx
On fresh new installation the `updateHasMore` would be undefined yet it's triggered so we perform a simple guard to ensure that it exists.
> Fix toggle error

- packages/api/resolvers/mutations/updateSubscription.js
- packages/core-subscriptions/db/subscriptions/helpers.js
- packages/core-subscriptions/plugins/licensed.js
This change will allow to change very basic subscription details like the actual product that defines the charging period and the quantity of the product, it fixes #264.
Currently, as long as a subscription is INITIAL, updatePlan will work accordingly but it fails when it's not INITIAL. Before merging this PR, we should add business logic to change an already active subscription's product.
What should happen in that case?
Active Subscription with Product A and 2 periods, one active:
1.2020 - 6.2020
6.2020 - 1.2021
Beeing at date 12.2020 we change the product to Product B which has another price and also is charged monthly so what happens is there will be another period added:
1.2020 - 6.2020
6.2020 - 1.2021 Product A
12.2020 - 1.2021 Product B
That's pretty fine but what if Product B is …
> Allow updating quantity and product of a subscription

- examples/controlpanel/components/InfiniteDataTable.jsx
- examples/controlpanel/components/SearchDropdown.jsx
- examples/controlpanel/components/orders/OrderList.jsx
- examples/controlpanel/components/resolveStatus.jsx
- examples/controlpanel/components/searchQueries.jsx
- packages/api/resolvers/queries/orders.js
- packages/api/resolvers/queries/ordersCount.js
- packages/api/schema/query.js
- packages/core-orders/db/orders/helpers.js
- packages/core-orders/db/orders/schema.js
test search valid  for
```
{ _id, userId,  orderNumber,  status  }
```
> Order search

- examples/minimal/boot.js
- packages/api/api.ts
- packages/api/createBulkImportServer.js
- packages/api/createGraphQLServer.js
- packages/api/resolvers/mutations/pageView.js
- packages/core-assortments/db/assortment-media/helpers.js
- packages/core-assortments/db/assortments/helpers.js
- packages/core-events/director.ts
- packages/core-events/index.ts
- packages/core-events/plugins/matomo-tracker.js
- packages/core-orders/db/order-payments/helpers.js
- packages/core-orders/db/order-positions/helpers.js
- packages/core-orders/db/orders/helpers.js
- packages/core-payment/plugins/apple-iap.js
- packages/core-payment/plugins/bity.js
- packages/core-payment/plugins/datatrans.js
- packages/core-payment/plugins/stripe-charges.js
- packages/core-payment/plugins/stripe.js
- packages/core-products/db/product-media/helpers.js
- packages/core-products/db/product-reviews/helpers.js
- packages/core-products/db/product-variations/helpers.js
- packages/core-products/db/products/helpers.js
- packages/core/core.js
- packages/utils/context.js
- packages/utils/utils.js
currently, the Product category is not available (in publicare context) unless we use tags here after.
> Matomo tracker update

- packages/core-products/src/db/ProductsSchema.js
`updateProductCommerce` currently fails with a type error
> Correct datatype for pricing.$.amount

- packages/core-events/tests/events-index.test.ts
The type filtering of the test is currently useless and all events are returned. It still passes, but it can be quite confusing for documentation purposes
> Fix events test

- packages/core-events/src/module/configureEventHistoryAdapter.ts
You currently need to dereference the inserted payload with event.payload.payload, fixes that and optionally passes context to the event.
> Fix EventHistoryAdapter

- packages/core-payment/plugins/cryptopay.ts
- packages/core-payment/plugins/postfinance-checkout/index.ts
- packages/core-payment/plugins/postfinance-checkout/middleware.ts
- packages/core-payment/plugins/postfinance-checkout/utils.ts
- tests/plugins-postfinance-checkout.test.js
- `checkout` instead of `markAsPaid`
- Removed unnecessary DB query in `charge` for Postfinance plugin
> Payment fixes

- packages/api/src/resolvers/mutations/enrollments/createEnrollment.ts
currently, enrollment can be created for any product and only when an adapter is when problem throws
```
No suitable enrollment plugin available for this plan configuration
```
but this should only be the case when a plan product has no configured subscription plan.
> Restrict enrollment to Plan_Product only

- packages/api/src/resolvers/mutations/bookmarks/createBookmark.ts
- packages/api/src/schema/mutation.ts
- packages/core-bookmarks/src/db/BookmarksSchema.ts
- packages/core-bookmarks/src/module/configureBookmarksModule.ts
- packages/types/bookmarks.ts
Includes bookmark extension that will enable projects to store and use additional bookmark information using meta fields
- Added meta on bookmarks db schema
- extend `mutation.createBookmark` to accept additional optional `meta` parameter
- extend BookmarkModule to include `deleteByUserIdAndMeta` util for performing bulk delete operation based on meta.
This PR is generic and doesn't implement the exact requirement we encountered for the favorite list on a project. Still, it will enable us to extend the functionality to the specific condition per project bases.
> Add meta on bokkmark schema

- docs/source/advanced-config/events.md
- packages/api/src/errors.ts
- packages/api/src/resolvers/mutations/bookmarks/bookmark.ts
- packages/api/src/resolvers/mutations/bookmarks/createBookmark.ts
- packages/api/src/resolvers/mutations/bookmarks/removeBookmark.ts
- packages/api/src/resolvers/type/user-types.ts
- packages/api/src/roles/loggedIn.ts
- packages/api/src/schema/mutation.ts
- packages/core-bookmarks/src/module/configureBookmarksModule.ts
- packages/core-bookmarks/src/service/migrateBookmarksService.ts
- packages/types/bookmarks.ts
While working with Bookmark on a project I encountered this issues and fixed them on this PR
- `mutation.bookmark` didn't accept `meta` while it's possible to do the same thing with `mutation.createBookmark` I think it would be great if it accepts too
- **BUG** update operations in bookmark module emitted `BOOKMARK_UPDATED` event but the registered bookmark module event is `BOOKMARKS_UPDATE` .
other than the above issues current bookmark module is flexible and stable enough to use it for different application :)
> Bookmark fix

- packages/core-payment/src/module/configurePaymentCredentialsModule.ts
- packages/core-users/src/module/configureUsersModule.ts
- packages/core-users/src/module/configureUsersWebAuthnModule.ts
- packages/core/src/services/deleteUser.ts
- packages/core/src/services/migrateUserData.ts
> User deletion
