unchainedshop/unchained

packages/core-products/db/products/helpers.js, packages/core-products/db/products/schema.js
fixes https://github.com/unchainedshop/unchained/issues/45
=> fix https://github.com/unchainedshop/unchained/issues/45

packages/core-delivery/plugins/send-mail.js, packages/core-orders/db/orders/helpers.js
this makes it easier to show the full name of a configured product.
=> add product and productOriginal texts to email deliver and confirmation email

controlpanel/components/account/FormSetRoles.jsx, controlpanel/components/products/FormEditProductCommerce.jsx, packages/api/resolvers/queries/productCatalogPrices.js, packages/api/resolvers/types/shop.js, packages/api/roles/index.js, packages/api/schema/types/shop.js, packages/core-quotations/db/quotations/helpers.js, packages/core-quotations/db/quotations/schema.js, packages/core-quotations/director.js, packages/platform/intercept-emails.js
…independent from introspection queries
=> Extendable user roles

packages/api/schema/types/user.js, packages/core-orders/db/orders/helpers.js, packages/core-users/db/helpers.js, packages/core-users/db/schema.js
fixes https://github.com/unchainedshop/unchained/issues/58
=> feat: expose lastContact on user

examples/controlpanel/components/Header.jsx, examples/controlpanel/components/LogList.jsx, examples/controlpanel/components/account/FormSignIn.jsx, examples/controlpanel/package-lock.json, examples/controlpanel/pages/logs/index.jsx, packages/api/resolvers/mutations/createFilter.js, packages/api/resolvers/mutations/createFilterOption.js, packages/api/resolvers/mutations/createProductVariation.js, packages/api/resolvers/mutations/createProductVariationOption.js, packages/api/resolvers/mutations/updateAssortmentTexts.js, packages/api/resolvers/mutations/updateFilterTexts.js, packages/api/resolvers/mutations/updateProductMediaTexts.js, packages/api/resolvers/mutations/updateProductTexts.js, packages/api/resolvers/mutations/updateProductVariationTexts.js, packages/core-assortments/db/helpers.js, packages/core-filters/db/helpers.js, packages/core-products/db/product-media/helpers.js, packages/core-products/db/product-variations/helpers.js, packages/core-products/db/products/helpers.js
Various small refactorings in controlpanel and internal upsertLocalizedText  methods
=> Consistent upsert text

examples/controlpanel/components/Redirect.jsx, examples/controlpanel/lib/connectApollo.jsx, examples/controlpanel/lib/initApollo.js, examples/controlpanel/lib/withCurrentUser.js, examples/controlpanel/next.config.js, examples/controlpanel/package-lock.json, examples/controlpanel/package.json
Minor changes that allow to next export the controlpanel. This helps support cases embedding the controlpanel in the engine backend project
=> Controlpanel exportability

packages/core-pricing/plugins/order-discount.js
reproduce:
add item with price 0 to cart,
add item with non-0 price
add discount on cart
total of cart will be NaN (or 0)
please verify the implementation
=> fix: if an order contains an item with price 0 and discount is applied, the total price becomes NaN

examples/minimal/boot.js, packages/core-assortments/db/helpers.js, packages/core-products/db/products/helpers.js, packages/utils/find-unused-slug.js, packages/utils/utils.js, readme.md
This is not an optimal implementation because we currently don't have a good concept for module-specific configuration.
=> Customizable slugs

examples/minimal/package-lock.json, examples/minimal/package.json, packages/api/resolvers/mutations/removeAssortmentProduct.js, packages/core-assortments/db/helpers.js, packages/core-products/db/products/helpers.js
This PR introduces a non-trivial way of sorting the product id's of an assortment so that sub-assortment productIds are broader represented.
=> Zip Tree by Deepness

packages/api/resolvers/types/index.js, packages/api/resolvers/types/loaded-filter-option.js, packages/api/resolvers/types/loaded-filter.js, packages/api/schema/types/assortment.js, packages/api/schema/types/filter.js, packages/core-filters/db/helpers.js
Currently working:
```graphql
query assortmentWithFilters($query: [FilterQueryInput!]) {
assortments {
products(query: $query) {
totalCount
filteredCount
items {
_id
}
}
filters(query: $query) {
examinedProducts
filteredProducts
isSelected
definition {
key
}
filteredOptions {
filteredProducts
isSelected
definition {
value
}
}
}
}
}
```
=> New filter

examples/minimal/package-lock.json, packages/api/errors.js, packages/api/resolvers/mutations/addProductReviewVote.js, packages/api/resolvers/mutations/index.js, packages/api/resolvers/mutations/removeProductReview.js, packages/api/resolvers/mutations/removeProductReviewVote.js, packages/api/resolvers/mutations/updateProductReview.js, packages/api/resolvers/types/user.js, packages/api/roles/admin.js, packages/api/roles/all.js, packages/api/roles/index.js, packages/api/roles/loggedIn.js, packages/api/schema/mutation.js, packages/api/schema/query.js, packages/core-products/db/product-reviews/helpers.js, packages/core-products/products-tests.js, tests/cart-checkout.test.js, tests/cart-discounts.test.js, tests/cart-quotations.test.js, tests/product-reviews.test.js, tests/seeds/products.js
This finished up the first minimal version of product reviews and adds test coverage
=> Product Reviews

packages/core-bookmarks/db/helpers.js, packages/platform/setup-accounts.js
Migrate bookmarks on login as we do with `carts`.
=> feat: migrate bookmarks on login

packages/core-users/db/helpers.js
fixes https://github.com/unchainedshop/unchained/issues/144
=> fix: send verification email to newly added email

packages/core-worker/plugins/http-request.js
=> Properly handle error

examples/minimal/boot.js, packages/core-delivery/db/helpers.js, packages/core-delivery/director.js, packages/core-delivery/settings.js, packages/core-orders/db/orders/helpers.js, packages/core-orders/orders.js, packages/core-payment/db/helpers.js, packages/core-payment/director.js, packages/core-payment/settings.js, readme.md
Fixes https://github.com/unchainedshop/unchained/issues/139
=> Supported providers

readme.md, tests/orders.test.js
added order query test for:
- list of user orders
- error for anonymous user order query
- single order by id query
=> Add order query tests

examples/controlpanel/components/BreadcrumbTrail.jsx, examples/controlpanel/components/assortments/AssortmentHeader.jsx, examples/controlpanel/components/products/ProductHeader.jsx
`BreadcrumbTrail` component is created and placed atop of products and assortments to showcase the links. But I'm still unsure if the links are being displayed correctly so please let me know what you think @pozylon
=> Add BreadcrumbTrail component

examples/controlpanel/components/SearchDropdown.jsx, examples/controlpanel/components/assortments/FormNewAssortmentLink.jsx
This PR replaces the dropdown at assortments linking with our search dropdown component. Also, the search component was modified to look as a normal uniforms component so now it turns red when form submission fails and what not.
=> Assortment to assortment linking dropdown

examples/controlpanel/components/assortments/AssortmentFilterListItem.jsx, examples/controlpanel/components/assortments/AssortmentLinkListItem.jsx, examples/controlpanel/components/assortments/FormNewAssortmentFilter.jsx
Give the assortment filters form a similar look to assortment linking.
=> Add tags to assortment filters

packages/api/roles/loggedIn.js, tests/bookmark.test.js, tests/helpers.js, tests/seeds/bookmark.js, tests/user-bookmarks.test.js
added failing bookmark tests that support issue #182
=> Add bookmark test

packages/api/resolvers/queries/users.js, packages/api/schema/query.js, packages/core-users/db/schema.js, packages/utils/utils.js, tests/auth-admin.test.js
Added search functionality to users query
https://github.com/unchainedshop/unchained/issues/226
=> Add queryString to users query

examples/controlpanel/components/BreadcrumbTrail.jsx, examples/controlpanel/components/products/ProductHeader.jsx
=> Fix assortments breadcrumb

packages/api/callMethod.js, packages/api/resolvers/mutations/accounts/loginAsGuest.js, packages/api/resolvers/mutations/accounts/loginWithPassword.js, packages/api/resolvers/mutations/accounts/logout.js, packages/core-accountsjs/core-accountsjs.js, packages/core-users/db/helpers.js
=> Convert logout to use accountjs

examples/controlpanel/components/Header.jsx, examples/controlpanel/semantic-ui/site/elements/button.overrides, examples/controlpanel/semantic-ui/site/globals/site.variables
I copied the [site configurations](https://github.com/Semantic-Org/Semantic-UI-LESS/blob/e4395217c1b8b3227c7387284d12f2d9774d33c6/themes/default/globals/site.variables) from the default theme then modified the colors to match Unchained website but I don't know if this is enough.
=> Set Unchained colors

examples/minimal/.meteor/versions, packages/core-accountsjs/accounts-server.js
Pumped the token validity time to ~30 days.
=> Increase token time

codeship-steps.yml, package-lock.json, package.json, packages/api/loaders/index.ts, packages/api/resolvers/queries/shopInfo.ts, packages/core-accountsjs/accounts.d.ts, packages/core-countries/countries.d.ts, packages/core-languages/languages.d.ts, packages/core-products/products.d.ts, packages/core-users/users.d.ts, packages/utils/utils.d.ts, patches/@types+meteor+1.4.64.patch
Dummy types to build upon to pass type checks and automatic type checking in CI
=> Fix typechecks

examples/minimal/.meteor/versions, examples/minimal/seed.js, packages/api/schema/types/assortment.js, packages/core-users/db/helpers.js, packages/platform/package.js, packages/platform/setup-accounts.js
I rebased on 0.61.x so everything I'm working on doesn't get funny when merging. but I encountered this error when I tried to delete the `meteor` and create a new one. this was the error
it has to do with the `createUser` function sending `emails` array instead of `email` but set enrollment is actually doing this
```
await accountsPassword.sendEnrollmentEmail(userData.email);
```
=> Hot fix user seed error

examples/controlpanel/components/products/ProductVariationAssignmentList.jsx, packages/core-products/db/products/helpers.js, tests/products.test.js, tests/seeds/products.js
=> Price resolver test

examples/minimal/.meteor/versions, examples/minimal/package-lock.json, packages/api/.versions, packages/api/package.js, packages/core-delivery/db/helpers.js, packages/core-messaging/.versions, packages/core-messaging/package.js, packages/core-messaging/worker/message.js, packages/core-pricing/.versions, packages/core-pricing/delivery-pricing/sheet.js, packages/core-pricing/order-pricing/sheet.js, packages/core-pricing/package.js, packages/core-pricing/payment-pricing/sheet.js, packages/core-pricing/pricing-sheet.js, packages/core-pricing/product-pricing/sheet.js, packages/core-products/.versions, packages/core-products/db/product-media/helpers.js, packages/core-products/db/products/helpers.js, packages/core-products/package.js
Merges the Hotfixes of the last couple weeks into vNext
=> Upstream patches

packages/api/schema/types/assortment.js, packages/api/schema/types/media.js, packages/api/schema/types/order/delivery.js, packages/api/schema/types/order/order.js, packages/api/schema/types/order/payment.js, packages/api/schema/types/payment.js, packages/api/schema/types/product/bundle-product.js, packages/api/schema/types/product/configurable-product.js, packages/api/schema/types/product/plan-product.js, packages/api/schema/types/product/product.js, packages/api/schema/types/product/simple-product.js, packages/api/schema/types/subscription.js
I've added deprecation warning on all revolvers for meta, we can add it now and proceed to 2 & 3 stated on #237
=> Add deprication warnings #237

docs/gatsby-config.js, docs/source/config/accounts.md, examples/minimal/boot.js, packages/core-accountsjs/settings.js
=> [URGENT] Fix accounts module in handling options parameter #358

changelog.md, packages/@unchainedshop/types/worker.ts, packages/api/src/resolvers/queries/index.js, packages/api/src/resolvers/queries/worker/workQueue.ts, packages/api/src/resolvers/queries/worker/workQueueCount.ts, packages/api/src/schema/inputTypes.js, packages/api/src/schema/query.js, packages/core-events/src/module/configureEventsModule.ts, packages/core-worker/src/module/configureWorkerModule.ts
Closes #401 
**Note: this PR is an extension of #459 and shares on some values so that should be merged before this**
=> Workqueue count api

packages/api/src/schema/inputTypes.js
added sequence to `UpdateAssortmentInput` :)
=> Add assortment sequence update

packages/api/src/resolvers/queries/orders/orders.ts, packages/api/src/resolvers/type/user-types.ts, packages/api/src/schema/query.js, packages/api/src/schema/types/user.js, packages/core-orders/src/module/configureOrdersModule-queries.ts, packages/core-quotations/src/module/configureQuotationsModule.ts, packages/types/orders.ts, packages/types/user.ts, tests/quotations.test.js
Adds
- orders sort
- `user.orders`, `user.quotations` & `user.enrollments` sort and queryString filters
related with #217
=> Add order sort

examples/kitchensink/index.html
admin UI sandbox needs to be deployed first
=> Add sanbox admin ui link

packages/api/src/errors.ts, packages/api/src/resolvers/mutations/assortments/addAssortmentLink.ts, packages/core-assortments/src/module/configureAssortmentLinksModule.ts
Closes #468 
I've also added a filter in the admin UI to not display assortments that are parents to an assortment. it will enforce this rule
=> Add cyclic assortment link detection #468

package-lock.json, packages/api/src/createGraphQLServer.ts, packages/api/src/errors.ts, packages/api/src/resolvers/mutations/accounts/changePassword.ts, packages/api/src/resolvers/mutations/accounts/createUser.ts, packages/api/src/resolvers/mutations/accounts/disableTOTP.ts, packages/api/src/resolvers/mutations/accounts/enableTOTP.ts, packages/api/src/resolvers/mutations/accounts/enrollUser.ts, packages/api/src/resolvers/mutations/accounts/forgotPassword.ts, packages/api/src/resolvers/mutations/accounts/loginWithPassword.ts, packages/api/src/resolvers/mutations/accounts/loginWithWebAuthn.ts, packages/api/src/resolvers/mutations/accounts/resetPassword.ts, packages/core-accountsjs/src/module/configureAccountsModule.ts
=> Map account errors #132

packages/api/src/errors.ts, packages/api/src/resolvers/mutations/products/removeProduct.ts, packages/core-enrollments/src/module/configureEnrollmentsModule.ts, packages/core-orders/src/module/configureOrderPositionsModule.ts, packages/core-products/src/module/configureProductsModule.ts, packages/core-products/src/service/removeProductService.ts, packages/core-quotations/src/module/configureQuotationsModule.ts, packages/types/enrollments.ts, packages/types/orders.positions.ts, packages/types/products.ts, packages/types/quotations.ts
=>  Improve Deletion of Products #477 

packages/core-enrollments/src/module/configureEnrollmentsModule.ts
=> Fix enrollment meta update

packages/api/src/resolvers/type/user-types.ts, packages/api/src/schema/types/user.ts
Quotations, Orders and Enrollments query in users collection should accept all the parameters available on the global queries
=> Consistent queries

docs/source/advanced-config/admin-ui.md, docs/source/advanced-config/custom-modules.md, docs/source/advanced-config/delivery.md, docs/source/advanced-config/entities.md, docs/source/advanced-config/events.md, docs/source/index.mdx, docs/source/quick-start.md
=> Fix: typos

package-lock.json, packages/api/src/resolvers/type/product/product-types.ts, packages/api/src/resolvers/type/user-types.ts, packages/api/src/roles/all.ts, packages/api/src/roles/index.ts, packages/api/src/roles/loggedIn.ts, packages/api/src/schema/types/product/bundle-product.ts, packages/api/src/schema/types/product/configurable-product.ts, packages/api/src/schema/types/product/plan-product.ts, packages/api/src/schema/types/product/product.ts, packages/api/src/schema/types/product/simple-product.ts, packages/api/src/schema/types/product/tokenized-product.ts, packages/api/src/schema/types/user.ts, packages/types/products.ts
=> User product reviews

changelog.md, package-lock.json, packages/api/src/resolvers/queries/index.ts, packages/api/src/resolvers/queries/users/validateResetPasswordToken.ts, packages/api/src/resolvers/queries/users/validateVerifyEmailToken.ts, packages/api/src/schema/query.ts
Added validation token verifier endpoint for both reset token and email verification token
- validateResetPasswordToken
- validateVerifyEmailToken
Closes #588
=> Token validator

packages/api/src/schema/types/shop.ts
=> Add target on externalLinks field 

packages/platform/src/startPlatform.ts
=> Env validity checker

packages/api/src/mcp/index.ts, packages/api/src/mcp/tools/delivery/deliveryInterfacesHandler.ts, packages/api/src/mcp/tools/delivery/deliveryProvidersListHandler.ts, packages/api/src/mcp/tools/order/getMonthlySalesBreakdownHandler.ts, packages/api/src/mcp/tools/order/getSalesSummaryHandler.ts, packages/api/src/mcp/tools/order/getTopCustomersHandler.ts, packages/api/src/mcp/tools/order/getTopSellingProductsHandler.ts, packages/api/src/mcp/tools/order/index.ts, packages/api/src/mcp/tools/order/ordersListHandler.ts, packages/api/src/mcp/tools/payment/paymentInterfacesHandler.ts, packages/api/src/mcp/tools/payment/paymentProvidersListHandler.ts, packages/api/src/mcp/tools/warehousing/warehousingInterfacesHandler.ts, packages/api/src/mcp/tools/warehousing/warehousingProvidersListHandler.ts, packages/api/src/mcp/utils/orderFilters.ts, packages/api/src/mcp/utils/sharedSchemas.ts, packages/api/src/resolvers/queries/orders/orders.ts, packages/api/src/resolvers/queries/orders/ordersCount.ts, packages/api/src/resolvers/queries/payment/paymentInterfaces.ts, packages/api/src/schema/inputTypes.ts, packages/api/src/schema/query.ts, packages/core-orders/src/db/OrdersCollection.ts, packages/core-orders/src/module/buildFindSelector.ts, packages/core-orders/src/module/configureOrderDeliveriesModule.ts, packages/core-orders/src/module/configureOrderPaymentsModule.ts, packages/core-orders/src/module/configureOrderPositionsModule.ts, packages/core-orders/src/module/configureOrdersModule-queries.ts, packages/plugins/src/files/gridfs/adapter.ts
=> Extend Query.orders filter options
